[package]
name = "manchester_os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9"
spin = { version = "0.9.8", features = ["once", "mutex"] }
volatile = "0.3.0"
x86_64 = "0.15.1"

[package.metadata.bootimage]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04"]
